#!/bin/bash
##############################################################################
#
# Module: ci/build-direct.sh
#
# Function:
#	Compile the LMIC examples for a given Arduino target across the
#	region/radio matrix using arduino-cli directly. Used by CI jobs
#	that can't go through mcci-catena/mcci-catena-ci's wrap script
#	(e.g. boards the wrap doesn't know about, like AVR Mega 2560 or
#	RP2350).
#
# Usage:
#	bash ci/build-direct.sh <fqbn> [<library-path>]
#
#	<fqbn>          Arduino fully-qualified board name to build for.
#	<library-path>  Defaults to the parent directory of this script.
#
##############################################################################

set -uo pipefail

if [[ $# -lt 1 ]]; then
	echo "usage: $0 <fqbn> [<library-path>]" >&2
	exit 2
fi

FQBN="$1"
THISDIR="$(cd "$(dirname "$0")" && pwd)"
LIB="${2:-$(cd "$THISDIR/.." && pwd)}"
LIBROOT="$(cd "$LIB/.." && pwd)"
PROJCFG="$LIB/project_config/lmic_project_config.h"

REGIONS=(us915 eu868 au915 as923 as923jp kr920 in866)
RADIOS=(sx1276 sx1272)

# Sketches with hardcoded Feather/M0 pinmaps that don't compile on
# non-Feather boards.
SKIP_SKETCHES=(
	raw-feather
	ttn-otaa-feather-us915
	ttn-otaa-feather-us915-dht22
	ttn-abp-feather-us915-dht22
)

# Per-FQBN extra skips
case "$FQBN" in
	arduino:avr:*)
		# ttn-otaa-sx1262 forces sx1262 at compile time, but the AVR
		# build matrix here is sx1276/sx1272 only.
		SKIP_SKETCHES+=(ttn-otaa-sx1262)
		;;
esac

PROJCFG_BAK="$PROJCFG.bak"
[[ -f "$PROJCFG" ]] && cp "$PROJCFG" "$PROJCFG_BAK"
restore() {
	if [[ -f "$PROJCFG_BAK" ]]; then
		mv "$PROJCFG_BAK" "$PROJCFG"
	fi
}
trap restore EXIT

failed=0
attempted=0
for sketch_dir in "$LIB"/examples/*/; do
	sketch_name=$(basename "$sketch_dir")
	skip=0
	for s in "${SKIP_SKETCHES[@]}"; do
		[[ "$sketch_name" == "$s" ]] && skip=1 && break
	done
	if [[ $skip -eq 1 ]]; then
		echo "::notice::skip $sketch_name (not applicable for $FQBN)"
		continue
	fi
	sketch_file="$sketch_dir$sketch_name.ino"
	[[ -f "$sketch_file" ]] || continue

	# Per-sketch region restriction: sketches that unconditionally call
	# region-specific LMIC entry points (e.g. LMIC_selectSubBand, only
	# defined for us915 and au915) won't link for other regions.
	sketch_regions=("${REGIONS[@]}")
	case "$sketch_name" in
		ttn-otaa-halconfig-us915)
			sketch_regions=(us915 au915)
			;;
	esac

	for radio in "${RADIOS[@]}"; do
		for region in "${sketch_regions[@]}"; do
			cat > "$PROJCFG" <<EOF
// generated by ci/build-direct.sh
#define CFG_${region} 1
#define CFG_${radio}_radio 1
#define DISABLE_PING
#define DISABLE_BEACONS
EOF
			attempted=$((attempted + 1))
			echo "==> $sketch_name region=$region radio=$radio fqbn=$FQBN"
			if ! arduino-cli compile \
					--fqbn "$FQBN" \
					--libraries "$LIBROOT" \
					--build-property "compiler.cpp.extra_flags=-DCOMPILE_REGRESSION_TEST" \
					"$sketch_dir"; then
				echo "::error::$sketch_name for $FQBN region $region radio $radio: compile failed"
				failed=$((failed + 1))
			fi
		done
	done
done

echo ""
echo "===================================================================="
echo "$FQBN build summary: attempted=$attempted failed=$failed"
echo "===================================================================="

[[ $failed -eq 0 ]] || exit 1
exit 0
