#!/bin/bash
##############################################################################
#
# Module: ci/build-avr-mega2560.sh
#
# Function:
#	Compile the LMIC examples for AVR Mega 2560 across the supported
#	region/radio matrix using arduino-cli directly. Mega 2560 has 256 KB
#	flash so every region+radio combination fits comfortably; no per-
#	region skipping is needed. We bypass mcci-catena-ci's wrap script
#	because it hardcodes feather32u4 as the AVR board.
#
# Usage:
#	bash ci/build-avr-mega2560.sh [<library-path>]
#
#	<library-path> defaults to the parent directory of this script.
#
##############################################################################

set -uo pipefail

THISDIR="$(cd "$(dirname "$0")" && pwd)"
LIB="${1:-$(cd "$THISDIR/.." && pwd)}"
LIBROOT="$(cd "$LIB/.." && pwd)"

FQBN="arduino:avr:mega:cpu=atmega2560"
REGIONS=(us915 eu868 au915 as923 as923jp kr920 in866)
RADIOS=(sx1276 sx1272)

# Sketches with hardcoded Feather/M0 pinmaps or hardware-specific deps that
# don't apply to Mega 2560.
SKIP_SKETCHES=(
	raw-feather
	ttn-otaa-feather-us915
	ttn-otaa-feather-us915-dht22
	ttn-abp-feather-us915-dht22
	ttn-otaa-sx1262
)

PROJCFG="$LIB/project_config/lmic_project_config.h"
PROJCFG_BAK="$PROJCFG.bak"
[[ -f "$PROJCFG" ]] && cp "$PROJCFG" "$PROJCFG_BAK"
restore() {
	if [[ -f "$PROJCFG_BAK" ]]; then
		mv "$PROJCFG_BAK" "$PROJCFG"
	fi
}
trap restore EXIT

failed=0
attempted=0
for sketch_dir in "$LIB"/examples/*/; do
	sketch_name=$(basename "$sketch_dir")
	skip=0
	for s in "${SKIP_SKETCHES[@]}"; do
		[[ "$sketch_name" == "$s" ]] && skip=1 && break
	done
	if [[ $skip -eq 1 ]]; then
		echo "::notice::skip $sketch_name (Feather/M0-specific or non-AVR radio)"
		continue
	fi
	sketch_file="$sketch_dir$sketch_name.ino"
	[[ -f "$sketch_file" ]] || continue

	for radio in "${RADIOS[@]}"; do
		for region in "${REGIONS[@]}"; do
			cat > "$PROJCFG" <<EOF
// generated by ci/build-avr-mega2560.sh
#define CFG_${region} 1
#define CFG_${radio}_radio 1
#define DISABLE_PING
#define DISABLE_BEACONS
EOF
			attempted=$((attempted + 1))
			echo "==> $sketch_name region=$region radio=$radio"
			if ! arduino-cli compile \
					--fqbn "$FQBN" \
					--libraries "$LIBROOT" \
					--build-property "compiler.cpp.extra_flags=-DCOMPILE_REGRESSION_TEST" \
					"$sketch_dir"; then
				echo "::error::$sketch_name for board mega2560 region $region radio $radio: compile failed"
				failed=$((failed + 1))
			fi
		done
	done
done

echo ""
echo "===================================================================="
echo "Mega 2560 build summary: attempted=$attempted failed=$failed"
echo "===================================================================="

[[ $failed -eq 0 ]] || exit 1
exit 0
